//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: game_network.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate GameNetwork_GreeterClient, then call methods of this protocol to make API calls.
internal protocol GameNetwork_GreeterClientProtocol: GRPCClient {
  var interceptors: GameNetwork_GreeterClientInterceptorFactoryProtocol? { get }

  func sayHello(
    _ request: GameNetwork_HelloRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<GameNetwork_HelloRequest, GameNetwork_HelloReply>
}

extension GameNetwork_GreeterClientProtocol {

  /// Sends a greeting.
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sayHello(
    _ request: GameNetwork_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<GameNetwork_HelloRequest, GameNetwork_HelloReply> {
    return self.makeUnaryCall(
      path: "/game_network.Greeter/SayHello",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }
}

internal protocol GameNetwork_GreeterClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'sayHello'.
  func makeSayHelloInterceptors() -> [ClientInterceptor<GameNetwork_HelloRequest, GameNetwork_HelloReply>]
}

internal final class GameNetwork_GreeterClient: GameNetwork_GreeterClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: GameNetwork_GreeterClientInterceptorFactoryProtocol?

  /// Creates a client for the game_network.Greeter service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: GameNetwork_GreeterClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol GameNetwork_GreeterProvider: CallHandlerProvider {
  var interceptors: GameNetwork_GreeterServerInterceptorFactoryProtocol? { get }

  /// Sends a greeting.
  func sayHello(request: GameNetwork_HelloRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GameNetwork_HelloReply>
}

extension GameNetwork_GreeterProvider {
  internal var serviceName: Substring { return "game_network.Greeter" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(
    _ methodName: Substring,
    callHandlerContext: CallHandlerContext
  ) -> GRPCCallHandler? {
    switch methodName {
    case "SayHello":
      return CallHandlerFactory.makeUnary(
        callHandlerContext: callHandlerContext,
        interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
      ) { context in
        return { request in
          self.sayHello(request: request, context: context)
        }
      }

    default:
      return nil
    }
  }
}

internal protocol GameNetwork_GreeterServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'sayHello'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSayHelloInterceptors() -> [ServerInterceptor<GameNetwork_HelloRequest, GameNetwork_HelloReply>]
}
